---

- name: Undeploy Apache Webserver
  gather_facts: false
  hosts: all 
  become: true
  tasks:

  - name: Remove installed packeges httpd and php 
    yum:
      name:
        - httpd
        - php
      state: absent
