---

- name: Undeploy Apache Webserver
  gather_facts: false
  hosts: webservers
  become: true
  tasks:

    - name: Remove httpd
      dnf:
        name:
          - httpd
          - php
        state: absent

