---
- name: Undeploy Apache Webserver
  gather_facts: false
  hosts: backend
  become: true
  tasks:
    - name: Remove installed packages httpd and php
      ansible.builtin.yum:
        name:
          - httpd
          - php
        state: absent

- name: Undeploy HAProxy
  gather_facts: false
  hosts: frontend
  become: true
  tasks:
    - name: Remove installed package haproxy
      ansible.builtin.yum:
        name:
          - haproxy
        state: absent

    - name: Restore SELinux defaults
      ansible.posix.seboolean:
        name: haproxy_connect_any
        state: false
        persistent: true
