---
- name: Ensure SELinux permits HAProxy
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: true
    persistent: true

- name: Ensure HAProxy is installed.
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  when: ansible_os_family == 'Debian'
  ansible.builtin.lineinfile:
    dest: /etc/default/haproxy
    regexp: ^ENABLED.+$
    line: ENABLED=1
    state: present

- name: Get HAProxy version.
  register: haproxy_version_result
  changed_when: false
  check_mode: false
  ansible.builtin.command: haproxy -v

- name: Set HAProxy version.
  ansible.builtin.set_fact:
    haproxy_version: "{{ '1.5' if '1.5.' in haproxy_version_result.stdout else '1.4' }}"

- name: Copy HAProxy configuration in place.
  notify: restart haproxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 420
    validate: haproxy -f %s -c -q

- name: Enable the firewall port for HAProxy stats page
  ansible.posix.firewalld:
    port: 8404/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Enable the firewall port for Apache forward to backend
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Ensure HAProxy is started and enabled on boot.
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true
